plugins {
    id 'com.android.application'
}

android {
    namespace 'net.one97.paytm'
    compileSdk 34

    defaultConfig {
        applicationId 'net.one97.paytm'
        minSdk 21
        targetSdk 34
        versionCode 7
        versionName '1.6'
    }

    signingConfigs {
        release {
            storeFile file('../skillx-release.keystore')
            storePassword 'skillx123'
            keyAlias 'skillx'
            keyPassword 'skillx123'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            applicationIdSuffix '.debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    ndkVersion '25.2.9519653'
}

dependencies {
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'com.google.zxing:core:3.5.3'
}
